
name: build-mesa

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Mesa Repository URL'
        required: false
        default: 'https://gitlab.freedesktop.org/mesa/mesa.git'
      repo_ref:
        description: 'Git Ref'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: windows-2025
    strategy:
      matrix:
        arch: [x86, x64, arm64]

    env:
      VULKAN_SDK_VERSION: "1.4.321.1"

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: mesa checkout
        run: |
          git clone --depth 1 --branch ${{ inputs.repo_ref }} ${{ inputs.repo_url }} mesa-repo

      - name: llvm version
        id: llvm-version
        shell: cmd
        run: |
          for /F "tokens=2 delims= " %%f in ('findstr /B /C:"set LLVM_VERSION=" build.cmd') do echo %%f>"%GITHUB_OUTPUT%"

      - name: llvm cache
        id: llvm-cache
        uses: actions/cache@v4
        with:
          path: llvm-${{ steps.llvm-version.outputs.LLVM_VERSION }}-${{ matrix.arch }}
          key: llvm-${{ steps.llvm-version.outputs.LLVM_VERSION }}-${{ matrix.arch }}

      - name: glslang version
        id: glslang-version
        shell: cmd
        run: |
          for /F "tokens=2 delims= " %%f in ('findstr /B /C:"set GLSLANG_VERSION=" build.cmd') do echo %%f>"%GITHUB_OUTPUT%"

      - name: glslang cache
        id: glslang-cache
        uses: actions/cache@v4
        with:
          path: glslang-${{ steps.llvm-version.outputs.GLSLANG_VERSION }}.install
          key: glslang-${{ steps.llvm-version.outputs.GLSLANG_VERSION }}

      - name: build
        id: build
        shell: cmd
        run: |
          call build.cmd mesa-repo ${{ matrix.arch }}

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mesa-${{ matrix.arch }}
          path: mesa-${{ matrix.arch }}.7z
          if-no-files-found: error
          compression-level: 0
